name: MatrixColorAPI
version: 'Build 2b'
main: net.matrixcreations.libraries.MatrixColorAPI
api-version: '1.16'
authors: [ MatrixCreations, ItsHarshXD ]
description: Intuitive Color Library for Minecraft Platforms.
